# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/WZC/Vivado_projects/n4ddr/perf_test_v0.01/soc_axi_perf_demo/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/signed_mult/signed_mult.xci
# IP: The module: 'signed_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WZC/Vivado_projects/n4ddr/perf_test_v0.01/soc_axi_perf_demo/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/signed_mult/signed_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signed_mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/WZC/Vivado_projects/n4ddr/perf_test_v0.01/soc_axi_perf_demo/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/signed_mult/signed_mult.xci
# IP: The module: 'signed_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WZC/Vivado_projects/n4ddr/perf_test_v0.01/soc_axi_perf_demo/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/signed_mult/signed_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signed_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
