# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/WZC/Vivado_projects/n4ddr/perf_test_v0.01/soc_axi_perf_demo/rtl/xilinx_ip/axi_ram/axi_ram.xci
# IP: The module: 'axi_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WZC/Vivado_projects/n4ddr/perf_test_v0.01/soc_axi_perf_demo/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/WZC/Vivado_projects/n4ddr/perf_test_v0.01/soc_axi_perf_demo/rtl/xilinx_ip/axi_ram/axi_ram.xci
# IP: The module: 'axi_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/WZC/Vivado_projects/n4ddr/perf_test_v0.01/soc_axi_perf_demo/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
